# GitHub Actions Workflow for Running Tests and Uploading Coverage to Coveralls

name: "main push"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: npm install
        run: npm install --save-dev c8 coveralls
          
      # Run tests and generate coverage report
      - name: Run tests with coverage
        run: npx c8 --reporter=lcov npm test

      # Upload coverage report to Coveralls
      - name: Coveralls
        if: always()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
